spring:
  data:
    mongodb:
      uri: mongodb://172.24.62.181:40000/test
    cassandra:
      keyspace-name: test
      contact-points: 172.24.62.181
  datasource:
    url: jdbc:mysql://172.24.62.181:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: codesafe
    password: codesafe
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*
